events {}

stream {
  upstream nifi_tls {
    hash $remote_addr consistent;
    server nifi1:8443;
    server nifi2:8443;
    server nifi3:8443;
  }

  server {
    listen 8443;
    proxy_pass nifi_tls;
  }
}
